update BitlyProvider to v4 API
mremi/UrlShortener pull request #21
Opened 2020-02-26 07:57 UTC by navitern

2020-02-27 17:46 UTC, mcaskill reviewed
Unfortunately, these changes do not work. The V4 API requires POST requests with payload in the body.

2020-02-27 17:48 UTC, mcaskill requested changes
The `validate()` also needs to be updated accordingly:

```php
/**
 * Validates the Bit.ly's response and returns it whether the status code is 200.
 *
 * @param string  $apiRawResponse
 * @param integer $statusCode
 *
 * @return object
 *
 * @throws InvalidApiResponseException
 */
private function validate($apiRawResponse, $statusCode)
{
    $response = json_decode($apiRawResponse);

    if (null === $response) {
        throw new InvalidApiResponseException('Bit.ly response is probably mal-formed because cannot be json-decoded.');
    }

    if ($statusCode < 200 || $statusCode >= 300) {
        throw new InvalidApiResponseException(sprintf('Bit.ly returned status code "%s" with message "%s"',
            $statusCode,
            property_exists($response, 'message') ? $response->message : ''
        ));
    }

    return $response;
}
```

2020-02-27 17:48 UTC, mcaskill commented on src/Mremi/UrlShortener/Provider/Bitly/BitlyProvider.php
> +        $response = $client->get(sprintf('/v4/shorten?longUrl=%s&domain=%s',
```php
$response = $client->post('/v4/shorten', array_merge(
    array(
        'json' => array(
            'domain'   => $domain,
            'long_url' => $link->getLongUrl(),
        ),
    ),
    $this->options
));
```

2020-02-27 17:48 UTC, mcaskill commented on src/Mremi/UrlShortener/Provider/Bitly/BitlyProvider.php
> +        $response = $client->get(sprintf('/v4/expand?shortUrl=%s&hash=%s',
```php
$response = $client->post('/v4/expand', array_merge(
    array(
        'json' => array(
            'bitlink_id' => $hash ?: $link->getShortUrl(),
        ),
    ),
    $this->options
));
```

2020-03-09 09:53 UTC, navitern commented
Yes, my mistake.

2020-03-09 09:53 UTC, closed without merging